import "./globals.css";
import {Montserrat} from 'next/font/google'
import { ToastContainer } from 'react-toastify';


const montserratFont = Montserrat({
  subsets:['latin'],
  weight:["400","500","600", "700", "800","900"],
  display:'swap'
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${montserratFont.className} antialiased`}
      >
        <ToastContainer />
        {children}
      </body>
    </html>
  );
}
